name: CI/CD Workflow for Flask App


on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  

      - name: Build Docker image
        run: |
          docker build -t calculator .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Your DockerHub username
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  # Your DockerHub password

      - name: Push Docker image to DockerHub
        run: |
          docker tag calci ${{ secrets.DOCKERHUB_USERNAME }}/calci:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/calci:latest